# Generated by Django 3.2.2 on 2021-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_all_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='timer',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daily',
            name='timer',
            field=models.CharField(default='00d:00hr:00min:00sec', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='timer',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
