# Generated by Django 3.2.2 on 2021-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210512_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timer',
        ),
        migrations.AddField(
            model_name='all',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
