# Generated by Django 3.2.2 on 2021-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210512_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('off', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
                ('expires', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
