# Generated by Django 3.2.2 on 2021-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210516_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
