# Generated by Django 3.2.2 on 2021-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='owner',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
    ]
